
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest0 {

  public static boolean debug = false;

  @Test
  public void test01() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test01"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", (int)(byte)10, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test02() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test02"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", (int)'4', secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test03() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test03"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", 1, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test04() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test04"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", 10, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test05() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test05"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", 10, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test06() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test06"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", (int)(short)100, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test07() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test07"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", (int)(byte)-1, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test08() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test08"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", (int)(byte)-1, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test09() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test09"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", (int)(byte)1, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test10() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test10"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", (int)(short)0, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test11() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test11"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", (int)(short)10, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test12() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test12"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", (int)' ', secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test13() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test13"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", (int)'a', secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test14() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test14"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", (int)(short)10, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test15() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test15"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", (int)'4', secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test16() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test16"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", (int)(byte)100, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test17() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test17"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", (int)'#', secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test18() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test18"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", 0, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test19() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test19"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", (int)(short)0, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test20() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test20"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", (int)(short)1, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test21() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test21"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", (int)' ', secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test22() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test22"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", (int)(short)100, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test23() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test23"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", (int)(short)-1, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test24() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test24"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", (int)(byte)10, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test25() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test25"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", 1, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test26() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test26"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", (int)(byte)100, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test27() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test27"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", (int)(byte)0, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test28() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test28"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", (int)(short)-1, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test29() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test29"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", 100, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test30() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test30"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", (int)(short)1, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test31() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test31"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", (-1), secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test32() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test32"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", (int)(byte)1, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test33() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test33"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", (int)(byte)0, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test34() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test34"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", (-1), secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test35() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test35"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", (int)'a', secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test36() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test36"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", 100, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test37() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test37"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("", (int)'#', secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test38() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test38"); }


    administrative.Secretary secretary2 = null;
    administrative.Secretary secretary3 = null;
    // The following exception was thrown during execution in test generation
    try {
    administrative.Departament departament4 = new administrative.Departament("hi!", 0, secretary2, secretary3);
      org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException");
    } catch (java.lang.NullPointerException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.NullPointerException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException, got " + e.getClass().getCanonicalName());
      }
    }

  }

}
